version: '3.8'

services:
  # Development container
  app-dev:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001/api
      - VITE_STYLES_SERVER_URL=http://localhost:3001/api/styles
      - VITE_MAPUTNIK_WEBHOOK_URL=http://localhost:3001/api/maputnik-webhook
    networks:
      - basemap-network
    profiles:
      - development

  # Production container
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
      - VITE_STYLES_SERVER_URL=${VITE_STYLES_SERVER_URL:-http://localhost:3001/api/styles}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_MAPUTNIK_WEBHOOK_URL=${VITE_MAPUTNIK_WEBHOOK_URL}
    networks:
      - basemap-network
    profiles:
      - production

  # API server (if self-hosting)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${VITE_SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./styles:/app/public/styles:ro
    networks:
      - basemap-network
    profiles:
      - api

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - basemap-network
    profiles:
      - production
      - api

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - app-prod
    networks:
      - basemap-network
    profiles:
      - production-ssl

volumes:
  redis-data:

networks:
  basemap-network:
    driver: bridge