version: '3.8'

services:
  mapconfig:
    build: .
    container_name: mapconfig-converter
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_SECRET=change-this-secret-in-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - mapconfig-network

  # Optional: Add nginx for production with SSL
  nginx:
    image: nginx:alpine
    container_name: mapconfig-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mapconfig
    restart: unless-stopped
    networks:
      - mapconfig-network

networks:
  mapconfig-network:
    driver: bridge